### ISSUE TITLE
Informative groupBy names

### ISSUE THREAD

**Issue by MayaGans** [gvwilson/tidyblocks#241]
In order to perform something like:

```
dat %>% group_by(days, outcome, group) %>%
  summarise(count = n()) %>%
  filter(outcome == "no event" && days == "days0_30")
````

https://github.com/tidyblocks/tidyblocks/tree/master/examples/open-intro-stats-hs/data-collection/section_1.1

I'd like to retain the columns we're grouping by so rather than the resulting grouped DF look like this:
<img width="1112" alt="Screen Shot 2019-10-25 at 7 42 13 AM" src="https://user-images.githubusercontent.com/6053906/67580659-8d56a200-f6fb-11e9-9568-54b87e248dc2.png">

It would have three more columns `days, outcome, group` corresponding to the _ group _ column. Is this doable?

**Comment by gvwilson** [comment]
So I think the problem is that `groupby` knows which columns are used for grouping, but `summarize` doesn't: we don't record the column names for grouping just the group ID, so by the time we hit the `summarize` block, we don't have the grouping values to display. We _could_ hold onto them in an auxiliary data structure of some sort, but then table display would become more complicated as well. We could also concatenate all of the grouping values and create a `_group_values_` column, but that would be very wide and unwieldy. Preferences?

**Comment by MayaGans** [comment]
Without knowing what the first option entails I think I might opt into the concat column as an immediate fix but open an issue for the first option/ something better?

**Comment by gvwilson** [comment]
Hi Maya,

OK, here's a new plan for grouping and summarize:

1. `groupBy` adds a `_group_` column with a group ID for each row based on values in selected columns (as it does now).

2. `summarize` calculates a summary value as it does now, but instead of collapsing rows, it adds those values (with a synthesized column name) to every record.

So using the colors data:

```
name    red     green   blue
black   0       0       0
red     255     0       0
maroon  128     0       0
lime    0       255     0
green   0       128     0
blue    0       0       255
navy    0       0       128
yellow  255     255     0
fuchsia 255     0       255
aqua    0       255     255
white   255     255     255
```

If we group by `red` we get three distinct groups:

```
name    red     green   blue    _group_
black   0       0       0       0
red     255     0       0       1
maroon  128     0       0       2
lime    0       255     0       0
green   0       128     0       0
blue    0       0       255     0
navy    0       0       128     0
yellow  255     255     0       1
fuchsia 255     0       255     1
aqua    0       255     255     0
white   255     255     255     1
```

Now let's count `green` values for each group. The existing implementation throws away the atomic columns and produces:

```
_group_ green_count
0       6
1       4
2       1
```

The new implementation would append `green_count` to every row:

```
name    red     green   blue    _group_ green_count
black   0       0       0       0       6
red     255     0       0       1       4
maroon  128     0       0       2       1
lime    0       255     0       0       6
green   0       128     0       0       6
blue    0       0       255     0       6
navy    0       0       128     0       6
yellow  255     255     0       1       4
fuchsia 255     0       255     1       4
aqua    0       255     255     0       6
white   255     255     255     1       4
```

If we only want red values and green counts for each group we can filter:

```
red     _group_ green_count
0       0       6
255     1       4
128     2       1
0       0       6
0       0       6
0       0       6
0       0       6
255     1       4
255     1       4
0       0       6
255     1       4
```

This is clearer if we sort:

```
red     _group_ green_count
0       0       6
0       0       6
0       0       6
0       0       6
0       0       6
0       0       6
128     2       1
255     1       4
255     1       4
255     1       4
255     1       4
```

and even clearer if we add a new `unique` block that takes multiple columns and produces rows that are unique within those columns, so `unique(red, _group_, green_count)` produces:

```
red     _group_ green_count
0       0       6
128     2       1
255     1       4
```

We can also add a `sort` block that sorts by multiple columns, so `sort(_group_)` on this data would be:

```
red     _group_ green_count
0       0       6
255     1       4
128     2       1
```

At this point, I think we can get rid of `ungroup` and create a complement to `select` called `drop` that throws columns away, so `ungroup()` would become `drop(_group_)`, leaving:

```
red     green_count
0       6
255     4
128     1
```

I think this is the easiest thing to implement - will it do what you want?
