### ISSUE TITLE
Prettify code spacing

### ISSUE THREAD

**Issue by MayaGans** [gvwilson/tidyblocks#34]
Add line separators in blocks so when code is generated it is easier to read

**Comment by gvwilson** [comment]
I've tried adding `\n` newlines to code chunks in #41 but they don't appear to break lines when the code is displayed - is it because the browser is ignoring them in the same way that it ignores line breaks inside a `<p>` tag when rendering HTML? Can we try changing the code display pane to be a `<pre>` ?

**Comment by MayaGans** [comment]
Closed with PR #52
