### ISSUE TITLE
How to select multiple columns?

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/tidyblocks#63]
The `select` block currently allows selection of a single column. We should think of a UI to allow selection of multiple columns *without* allowing people to type multiple column names into a single field because that would be sinful.

**Comment by MayaGans** [comment]
I was using the variable_logical block `and` to drag in multiple columns in order to minimize the number of blocks, but maybe we should have a comma block? 

<img width="365" alt="Screen Shot 2019-08-21 at 6 57 24 AM" src="https://user-images.githubusercontent.com/6053906/63433726-01658880-c3e1-11e9-89e1-04ad3aead50a.png">

**Comment by gvwilson** [comment]
That will work, but then AND is serving two purposes (logical combination and multiple column selection). I remember asking this before, but is there a way to create a block that gets wider as needed?

Initial state: `[column name] +add`

after filling in a column name: `[Petal_Length] +add`

after clicking `+add`: `[Petal_Length] [column name] +add`

after filling in and clicking again: `[Petal_Length] [Sepal_Width] +add`

and so on. Is that possible?

**Comment by gvwilson** [comment]
Replaced by #80.
